openapi: 3.0.3

info:
  title: API
  version: 1.0.0

paths:
  /payment/userbalance:
    get:
      summary: Получить баланс
      tags:
        - payment
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: integer