openapi: 3.0.3

info:
  title: API
  version: 1.0.0

paths:
  /payment/userbalance:
    get:
      summary: Получить баланс
      tags:
        - payment
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: integer

    post:
      summary: Списание баланса
      tags:
        - payment
      requestBody:
        description: сумма к оплате
        content:
          'application/json':
            schema:
              type: object
              properties:
                amount:
                  type: integer
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: integer
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                type: integer