services:
  postgres-myshop-db:
    image: 'postgres:16.2-alpine'
    container_name: 'postgres-myshop-db'
    ports:
      - '5432:5432'
    volumes:
      - './.postgres-data:/var/lib/postgresql/myshop/data'
    environment:
      LC_ALL: 'C.UTF-8'
      #    задать пользователя
      POSTGRES_USER: 'admin'
      #    задать пароль
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'myshop'
      PGDATA: '/var/lib/postgresql/data'
    restart: unless-stopped


  redis:
    image: redis:7.4.2-bookworm
    container_name: redis_container
#    environment:
#      - REDIS_PASSWORD=admin
#      - REDIS_USER=my_user
#      - REDIS_USER_PASSWORD=my_user_password
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      sh -c '
        redis-server
        sleep 7
        redis-cli
      '
#      sh -c '
#        mkdir -p /usr/local/etc/redis &&
#        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
#        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
#        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
#        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
#        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
#        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
#        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
#      '
#    healthcheck:
#      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true